/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Component;
import java.awt.PopupMenu;
import java.awt.event.ActionListener;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import model.Aplikasi;
import model.View;

/**
 *
 * @author Kurniawan
 */
public class Main extends javax.swing.JFrame implements View {

    /**
     * Creates new form MainAdmin
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        label1 = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        beranda = new javax.swing.JMenu();
        akun = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        mpetugas = new javax.swing.JMenu();
        addPetugas = new javax.swing.JMenuItem();
        petugas = new javax.swing.JMenuItem();
        cariPetugas = new javax.swing.JMenuItem();
        delPetugas = new javax.swing.JMenuItem();
        mpelanggan = new javax.swing.JMenu();
        pelanggan = new javax.swing.JMenuItem();
        datPelanggan = new javax.swing.JMenuItem();
        cariPelanggan = new javax.swing.JMenuItem();
        delPelanggan = new javax.swing.JMenuItem();
        wisata = new javax.swing.JMenu();
        tempat = new javax.swing.JMenuItem();
        datTempat = new javax.swing.JMenuItem();
        cariTempat = new javax.swing.JMenuItem();
        delTempat = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        paket = new javax.swing.JMenuItem();
        datPaket = new javax.swing.JMenuItem();
        cariPaket = new javax.swing.JMenuItem();
        delPaket = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        jalan = new javax.swing.JMenuItem();
        addTransaksi = new javax.swing.JMenuItem();
        datJalan = new javax.swing.JMenuItem();
        cariJalan = new javax.swing.JMenuItem();
        delJalan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        label1.setFont(new java.awt.Font("DINPro-Black", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(102, 102, 102));
        label1.setText("BIRO PERJALANAN MERDEKA");

        beranda.setText("Beranda");
        beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                berandaMouseClicked(evt);
            }
        });
        beranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berandaActionPerformed(evt);
            }
        });

        akun.setText("Akun");
        akun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akunActionPerformed(evt);
            }
        });
        beranda.add(akun);

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        beranda.add(logout);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        beranda.add(exit);

        jMenuBar1.add(beranda);

        mpetugas.setText("Petugas");
        mpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpetugasActionPerformed(evt);
            }
        });

        addPetugas.setText("Add Petugas");
        addPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPetugasActionPerformed(evt);
            }
        });
        mpetugas.add(addPetugas);

        petugas.setText("Data Petugas");
        petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petugasActionPerformed(evt);
            }
        });
        mpetugas.add(petugas);

        cariPetugas.setText("Cari Petugas");
        cariPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariPetugasActionPerformed(evt);
            }
        });
        mpetugas.add(cariPetugas);

        delPetugas.setText("Delete Petugas");
        delPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delPetugasActionPerformed(evt);
            }
        });
        mpetugas.add(delPetugas);

        jMenuBar1.add(mpetugas);

        mpelanggan.setText("Pelanggan");
        mpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpelangganActionPerformed(evt);
            }
        });

        pelanggan.setText("Add Pelanggan");
        pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganActionPerformed(evt);
            }
        });
        mpelanggan.add(pelanggan);

        datPelanggan.setText("Data Pelanggan");
        datPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datPelangganActionPerformed(evt);
            }
        });
        mpelanggan.add(datPelanggan);

        cariPelanggan.setText("Cari Pelanggan");
        cariPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariPelangganActionPerformed(evt);
            }
        });
        mpelanggan.add(cariPelanggan);

        delPelanggan.setText("Del Pelanggan");
        delPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delPelangganActionPerformed(evt);
            }
        });
        mpelanggan.add(delPelanggan);

        jMenuBar1.add(mpelanggan);

        wisata.setText("Wisata");

        tempat.setText("Tempat");
        tempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempatActionPerformed(evt);
            }
        });
        wisata.add(tempat);

        datTempat.setText("Data Tempat");
        datTempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datTempatActionPerformed(evt);
            }
        });
        wisata.add(datTempat);

        cariTempat.setText("Cari Tempat");
        cariTempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariTempatActionPerformed(evt);
            }
        });
        wisata.add(cariTempat);

        delTempat.setText("Delete Tempat");
        delTempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delTempatActionPerformed(evt);
            }
        });
        wisata.add(delTempat);

        jMenuBar1.add(wisata);

        jMenu1.setText("Paket");

        paket.setText("Paket");
        paket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paketActionPerformed(evt);
            }
        });
        jMenu1.add(paket);

        datPaket.setText("Data Paket");
        datPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datPaketActionPerformed(evt);
            }
        });
        jMenu1.add(datPaket);

        cariPaket.setText("Cari Paket");
        cariPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariPaketActionPerformed(evt);
            }
        });
        jMenu1.add(cariPaket);

        delPaket.setText("Delete Paket");
        delPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delPaketActionPerformed(evt);
            }
        });
        jMenu1.add(delPaket);

        jMenuBar1.add(jMenu1);

        transaksi.setText("Transaksi");
        transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiActionPerformed(evt);
            }
        });

        jalan.setText("Add Perjalanan");
        jalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jalanActionPerformed(evt);
            }
        });
        transaksi.add(jalan);

        addTransaksi.setText("Add Transaksi");
        transaksi.add(addTransaksi);

        datJalan.setText("Data Perjalanan");
        datJalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datJalanActionPerformed(evt);
            }
        });
        transaksi.add(datJalan);

        cariJalan.setText("Cari Perjalanan");
        cariJalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariJalanActionPerformed(evt);
            }
        });
        transaksi.add(cariJalan);

        delJalan.setText("Delete Perjalanan");
        delJalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delJalanActionPerformed(evt);
            }
        });
        transaksi.add(delJalan);

        jMenuBar1.add(transaksi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void berandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_berandaMouseClicked

    private void berandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berandaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_berandaActionPerformed

    private void mpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpelangganActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mpelangganActionPerformed

    private void transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_transaksiActionPerformed

    private void paketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paketActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_paketActionPerformed

    private void mpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpetugasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mpetugasActionPerformed

    private void tempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempatActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tempatActionPerformed

    private void akunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akunActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_akunActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_logoutActionPerformed

    private void petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petugasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_petugasActionPerformed

    private void pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_pelangganActionPerformed

    private void jalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jalanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jalanActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_exitActionPerformed

    private void delPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delPelangganActionPerformed

    private void cariPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariPetugasActionPerformed

    private void addPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPetugasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addPetugasActionPerformed

    private void delPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delPetugasActionPerformed

    private void datPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datPelangganActionPerformed

    private void cariPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariPelangganActionPerformed

    private void datTempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datTempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datTempatActionPerformed

    private void cariTempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariTempatActionPerformed

    private void delTempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delTempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delTempatActionPerformed

    private void datPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datPaketActionPerformed

    private void cariPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariPaketActionPerformed

    private void delPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delPaketActionPerformed

    private void datJalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datJalanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datJalanActionPerformed

    private void cariJalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariJalanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariJalanActionPerformed

    private void delJalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delJalanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delJalanActionPerformed
    
    public Object getPaket() {
        return paket;
    }
    
    public Object getPelanggan() {
        return pelanggan;
    }
    
    public Object getPetugas() {
        return petugas;
    }
    
    public Object getTempat() {
        return tempat;
    }
    
    public Object getTransaksi() {
        return transaksi;
    }
    
    public Object getAkun() {
        return akun;
    }
    
    public Object getJalan() {
        return jalan;
    }
    
    public Object getLogout() {
        return logout;
    }

    public Object getCariJalan() {
        return cariJalan;
    }

    public Object getCariPaket() {
        return cariPaket;
    }

    public Object getCariPelanggan() {
        return cariPelanggan;
    }

    public Object getCariPetugas() {
        return cariPetugas;
    }

    public Object getCariTempat() {
        return cariTempat;
    }

    public Object getDatJalan() {
        return datJalan;
    }

    public Object getDatPaket() {
        return datPaket;
    }

    public Object getDatPelanggan() {
        return datPelanggan;
    }

    public Object getDatTempat() {
        return datTempat;
    }

    public Object getDelJalan() {
        return delJalan;
    }

    public Object getDelPaket() {
        return delPaket;
    }

    public Object getDelPelanggan() {
        return delPelanggan;
    }

    public Object getDelPetugas() {
        return delPetugas;
    }

    public Object getDelTempat() {
        return delTempat;
    }

    public Object getDesktopPane() {
        return desktopPane;
    }

    public void setDesktopPane(Component d) {
        this.desktopPane.add(d);
    }
    public void setRemoveDP(){
        desktopPane.removeAll();
    }
    public Object getAddPetugas() {
        return addPetugas;
    }

    public Object getExit() {
        return exit;
    }

    public Object getAddTransaksi() {
        return addTransaksi;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addPetugas;
    private javax.swing.JMenuItem addTransaksi;
    private javax.swing.JMenuItem akun;
    private javax.swing.JMenu beranda;
    private javax.swing.JMenuItem cariJalan;
    private javax.swing.JMenuItem cariPaket;
    private javax.swing.JMenuItem cariPelanggan;
    private javax.swing.JMenuItem cariPetugas;
    private javax.swing.JMenuItem cariTempat;
    private javax.swing.JMenuItem datJalan;
    private javax.swing.JMenuItem datPaket;
    private javax.swing.JMenuItem datPelanggan;
    private javax.swing.JMenuItem datTempat;
    private javax.swing.JMenuItem delJalan;
    private javax.swing.JMenuItem delPaket;
    private javax.swing.JMenuItem delPelanggan;
    private javax.swing.JMenuItem delPetugas;
    private javax.swing.JMenuItem delTempat;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jalan;
    private java.awt.Label label1;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenu mpelanggan;
    private javax.swing.JMenu mpetugas;
    private javax.swing.JMenuItem paket;
    private javax.swing.JMenuItem pelanggan;
    private javax.swing.JMenuItem petugas;
    private javax.swing.JMenuItem tempat;
    private javax.swing.JMenu transaksi;
    private javax.swing.JMenu wisata;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addListener(ActionListener ae) {
        akun.addActionListener(ae);
        logout.addActionListener(ae);
        exit.addActionListener(ae);
        
        addPetugas.addActionListener(ae);
        petugas.addActionListener(ae);
        cariPetugas.addActionListener(ae);
        delPetugas.addActionListener(ae);
        
        pelanggan.addActionListener(ae);
        datPelanggan.addActionListener(ae);
        cariPelanggan.addActionListener(ae);
        delPelanggan.addActionListener(ae);
        
        tempat.addActionListener(ae);
        datTempat.addActionListener(ae);
        cariTempat.addActionListener(ae);
        delTempat.addActionListener(ae);
        
        paket.addActionListener(ae);
        datPaket.addActionListener(ae);
        cariPaket.addActionListener(ae);
        delPaket.addActionListener(ae);
        
        jalan.addActionListener(ae);
        addTransaksi.addActionListener(ae);
        datJalan.addActionListener(ae);
        cariJalan.addActionListener(ae);
        delJalan.addActionListener(ae);
    }
}
